### ISSUE TITLE
Very different performance on get

### ISSUE THREAD

**Issue by earino** [bluefeet/Moo-se-Bench#1]
Hi Aran!

Benchmarks are the best. I was looking at this and one thing immediately stood out is the "get" section. Having the rates come out to exactly 2857143 blew my mind. I tested on my laptop macbook pro 2.7 ghz i7. With perl 5.18 and the latest Moose/Moo from CPAN I got different results from yours:

```
$ perl ./reader.pl
            Rate Moose   Moo
Moose  2881844/s    --  -73%
Moo   10869565/s  277%    --
Eduardos-MacBook-Pro-5:~ earino$ perl -v

This is perl 5, version 18, subversion 1 (v5.18.1) built for darwin-2level

Copyright 1987-2013, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```
Which really makes Moo look good for reading a ton properties... but this is with 5.18. I switch in perlbrew over to 5.20 and:

```
$ perl reader.pl
           Rate   Moo Moose
Moo   3571429/s    --   -7%
Moose 3846154/s    8%    --
eduardos-mbp-5:~ earino$ perl -v

This is perl 5, version 20, subversion 2 (v5.20.2) built for darwin-2level

Copyright 1987-2015, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```
Which are much closer than your numbers, but definitely not exactly the same.  However, the thing that *really* surprised me is the rate dropped from 10,869,565/s to 3,846,154/s in the upgrade from 5.18 to 5.20! 

Anyways, not sure where to take the testing from here?

**Comment by bluefeet** [comment]
Hey man!

On the moose@perl.org mailing list which I posted these benchmarks to someone suggested that a matrix of perl versions would be helpful, which I've added to the TODO.  I'm starting to envision a multidimensional benchmark.  :-O

So, Perl 5.20 makes Moo slower and Moose faster?  Thats really weird.

As far as getting the exact same numbers in my benchmark, I was puzzled by that too when I made it.  So, I ran it again, and the numbers matched again.  I was like WTF and checked the code, all was well.  I ran it a bunch more times and it didn't happen except for those first two.  Maybe I just have really good luck?  Anyways, I thought it was fun to use the first one.

**Comment by earino** [comment]
Under 5.18 Moo does 2,881,844/s
Under 5.20 Moo does 3,571,429/s 

So upgrading perl from 5.18 to 5.20 speeds up accessing a property in Moo by 19%

Under 5.18 Moose does 10,869,565/s
Under 5.20 Moose does  3,846,154/s

So upgrading perl from 5.18 to 5.20 slows down accessing a property in Moose code by 64%

It seems Perl 5.20 makes Moo faster and Moose much slower, for this one particular operation.

**Comment by bluefeet** [comment]
I just updated the benchmarks to call `make_immutable`.  I can't believe I forgot that.  This definitely improved Moose's standing, but not enough to change the conclusions.

**Comment by earino** [comment]
Yeah, working with Szilard on https://github.com/szilard/benchm-ml made it very clear, benchmarks are *hard*. Cheers! Let's grab lunch/breakfast/dinner!
